### ISSUE TITLE
How to activate the tab completion

### ISSUE THREAD

**Issue by FelixAkk** [mklabs/node-tabtab#12]
Hi, I'm having some trouble with getting tab completion working. Right now I have a file called `test` with the example snippet, but when I try to tabtab with `node test -` or `./test -` I get nothing. With double dash also nothing, and without the dash the regular autocompletion of files in the current directory.

I also tried putting some console.logs in the snippet to see if it's being fired at all, but no signs of it. Is there something obvious I'm missing here? I'm running on MacOS10.10, bash 3.2, node 0.12.0 and the latest node-tabtab. Thanks!

**Comment by mklabs** [comment]
Hi @FelixAkk 

I'm sorry, nothing obvious I can see from there. Are you still running into this issue ?

Have you added the completion script into your `.bashrc` ?

**Comment by FelixAkk** [comment]
I haven't added anything to my `.bashrc`, I wasn't aware that this was needed. I assume that anyone using my package which depends on this would then have to manually extend their `.bashrc`? Or do you know if there is a more user friendly way of doing this for users?

**Comment by mklabs** [comment]
v1 introduces a better way to install and activate completion on user machines, see https://github.com/mklabs/node-tabtab#automatic-installation

Let me know if you have additional questions.
