### ISSUE TITLE
script in .bashrc prevents autocompletion of file path

### ISSUE THREAD

**Issue by coder13** [mklabs/node-tabtab#14]
I'm using this module for one of my tools that autocompletes based off of the first argument, but the first argument must be a file path. I don't know how to enable filepath autocompletion for the first argument beyond coding it myself.

**Comment by mklabs** [comment]
Hi @coder13 

Sorry for the delay.

The default behavior should be shell filepath autocompletion if you don't provide any completion results. If that's not the case, it should be fixed.

tabtab have been reworked for v1.0.0, i'm going to close this isssue. If it's still relevant with latest version, please reopen.
