### ISSUE TITLE
`COMP_WORDBREAKS` exclusion option

### ISSUE THREAD

**Issue by malandrew** [mklabs/node-tabtab#15]
Currently, the script lifted from npm uses npm's list of wordbreak characters, which explicitly excludes the `@` symbol and the `=`. Furthermore, it modifies the global env variable `COMP_WORDBREAKS`, which is the wrong way to exclude characters per this SO answer: https://stackoverflow.com/questions/10528695/how-to-reset-comp-wordbreaks-without-effecting-other-completion-script

https://github.com/mklabs/node-tabtab/blob/master/lib/completion.sh#L14-L16

**Comment by mklabs** [comment]
Hi @malandrew 

Sorry for the delay. I'm going to close this issue, tabtab has been rewritten for v1.0.0, and the shell scripts have been reworked to https://github.com/mklabs/node-tabtab/tree/master/scripts

If you have any suggestion / improvements, please fill in another issue or a PR fixing those issues. I'm not very familiar to how bash completion works and how `COMP_WORDBREAKS` should be handled.
