### ISSUE TITLE
Release to npm?

### ISSUE THREAD

**Issue by joshbetz** [mklabs/node-tabtab#28]
The latest release is 1.3.2 on https://www.npmjs.com/package/tabtab

**Comment by mklabs** [comment]
Sure thing, I'll try to publish a new release shortly.

**Comment by mklabs** [comment]
Just published 1.4.3 which hopefully include the fix for your `--auto` issue. Let me know if that's not the case.

**Comment by joshbetz** [comment]
Looks fixed. Thanks!

**Comment by mklabs** [comment]
Hi @joshbetz I unpublished 1.4.3 in favor to a new one 2.0.0, because of yeoman/yo#441

**Comment by joshbetz** [comment]
Yeah, I bumped to 2.0.0. Thanks for the heads up.
