### ISSUE TITLE
Using tabtab from package.json

### ISSUE THREAD

**Issue by tsriram** [mklabs/node-tabtab#29]
I have specified the options in package.json and calling `require('tabtab')().start()` from the bin file. Have also used auto install script and it's getting installed in ~/.bashrc too. But I don't see any completion option that I have specified in package.json. 

Is there any example on how to use this with static completion options given in package.json? Any help would be appreciated.

**Comment by mklabs** [comment]
Hi  @tsriram 

You can find an example with: https://github.com/mklabs/node-tabtab/blob/master/examples/yo-complete/package.json#L34

Let me know if that works for you. I didn't tested completion based off a package.json for a while.

**Comment by mklabs** [comment]
There is also the nvm example in the [readme](https://github.com/mklabs/node-tabtab#nvm) I hope this helps.

**Comment by tsriram** [comment]
Couldn't get it working yet :(

Say if I have a module which gets installed globally, can I include `tabtab` property in it's own package.json and just call `require('tabtab')().start()` from it's bin file? Is that enough? yo-complete example has a `complete-generators` file which uses EventEmitter API - is it necessary?

Sorry if it's silly :grin:

**Comment by mklabs** [comment]
You have two ways to work with tabtab. If you include tabtab directly in your package / module, you should be able to get it working. Do you mind sharing your module so that I can maybe help you debug what's going on ?

**Comment by tsriram** [comment]
I'm working on cheminfo/tools#169 and trying to get tabtab working. You can take a look at the repo here - https://github.com/tsriram/tools/tree/issue_169. Have just edited package.json & bin/cheminfo.js.

Appreciate your help!

**Comment by mklabs** [comment]
It seems like your module doens't use the same name as the binary you are exposing. eg. cheminfo-tools vs cheminfo.

You need to specify `--name cheminfo` in the script.install section. eg.

```json
  "install": "tabtab install --name cheminfo --auto"
```

Be sure to remove the line added before by tabtab in your bashrc, and sourcing it again when you test it (or opening a new shell). By doing so, I was able to get completion results based off your package.json list.

**Comment by tsriram** [comment]
Ah, got it. Working fine now. Thanks a lot for the help.

**Comment by mklabs** [comment]
:+1:
