### ISSUE TITLE
autocomplete context

### ISSUE THREAD

**Issue by rauluranga** [mklabs/node-tabtab#8]
Hi again!
when running autocomplete from CLI it also prints other commands from OSX, mostly folders on the current path (im using oh-my-zsh)
to fix this issue, i just updated completion template to the following:
(borrowed from [bower autocomplete](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/bower/_bower) from oh-my-zsh)

```bash
# Credits to npm's awesome completion utility.
### credits to npm, this file is coming directly from isaacs/npm repo
#
# Just testing for now. (trying to learn this cool stuff)
#
# npm command completion script
#
# Installation: {completer} completion >> ~/.bashrc  (or ~/.zshrc)
#

COMP_WORDBREAKS=${COMP_WORDBREAKS/=/}
COMP_WORDBREAKS=${COMP_WORDBREAKS/@/}
export COMP_WORDBREAKS

if type complete &>/dev/null; then
  _{pkgname}_completion () {
    local si="$IFS"
    IFS=$'\n' COMPREPLY=($(COMP_CWORD="$COMP_CWORD" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           {pkgname} completion -- "${COMP_WORDS[@]}" \
                           2>/dev/null)) || return $?
    IFS="$si"
  }
  complete -F _{pkgname}_completion {pkgname}
elif type compctl &>/dev/null; then
  _{pkgname}_completion () {
    local cword line point words si
    read -Ac words
    read -cn cword
    let cword-=1
    read -l line
    read -ln point
    si="$IFS"
    IFS=$'\n' reply=($(COMP_CWORD="$cword" \
                       COMP_LINE="$line" \
                       COMP_POINT="$point" \
                       {pkgname} completion -- "${words[@]}" \
                       2>/dev/null)) || return $?
    IFS="$si"
  }
  compctl -K _{pkgname}_completion {pkgname}
fi
###-end-{pkgname}-completion-###	
```

**Comment by plentybinary** [comment]
Hey have you found a way to make this global for users after install? I can add it to my own ~/.bashrc but I would rather find a way to do it automatically for users who download my package.

**Comment by mklabs** [comment]
Hello @rauluranga @plentybinary 

> Hey have you found a way to make this global for users after install? I can add it to my own ~/.bashrc but I would rather find a way to do it automatically for users who download my package.

Depends from system to system, but I don't recommend it. This is pretty obtrusive, and npm doesn't do that (as far as I know), I'd rather not force anything global on a package download.

However, when you install git (again depends on the packaging), the completion helpers are automatically installed, might be worth checking out.
