### ISSUE TITLE
need a new release..

### ISSUE THREAD

**Issue by GuyMograbi** [mklabs/node-tabtab#9]
you have a very important fix merged at february 2014, however 0.0.2 - your latest release was on january 2014.. 

you should have a new version released. it is a crucial bug regarding `--` completion. 

I just spent 2 hours from my life hacking through it until I noticed someone fixed it. 

BTW - cool library! why did you stop deveoping it? there's more potential - like integration with commander library.. 

thanks.

**Comment by mklabs** [comment]
Hi @GuyMograbi 

Sorry for that. I just published a new version.
